print('olá seja bem vindo a melhor loja de games do brasil')
nome = input ('coloque aqui seu nome: ')
print('olá' ,nome, 'é um prazer estar aqui com voce hoje')
jogo = input('coloque aqui o jogo que voce deseja: ')
valor = input('coloque aqui o valor minimo: ')
tempo = input('coloque aqui o tempo minimo de espera: ')
print('o jogo que voce deseja é' ,jogo,)
print('o valor minimo que voce deseja pagar é' ,valor,)
print('o tempo minimo que voce deseja que chegue em sua casa é' ,tempo,)
corretas = input('informaçoes estao corretas? ')
salvar = input ('deseja salvar as informaçoes? ')
print('informaçoes salvas com sucesso')
